### ISSUE TITLE
Q: is ti possible to generate man page using mdformat-toc?

### ISSUE THREAD

**Issue by kloczek** [hukkin/mdformat-toc#9]
Sphinx allows render documentation to +10 output formats.
I found that few python modules started using mdformat-toc and as man page still is basic Unix documenation format I'm interested durting builgin rpm/Solaris IPS packages to provide module documentation as man page.

**Comment by hukkin** [comment]
mdformat-toc is an mdformat plugin and mdformat outputs Markdown only (because it is a Markdown formatter). There is no man page support.
